export interface Player {
  id: string;        // Persistent UUID (generated by client, stored in localStorage)
  socketId: string;  // Current socket connection (changes on reload)
  name: string;
  isHost: boolean;
  joinedAt: number;
  estimation?: boolean; // Has submitted answer
  animalIcon?: string;  // Emoji assigned by server on join
  disconnectedAt?: number; // Set when player disconnects, cleared on reconnect
}

export interface GameSession {
  roomCode: string;
  createdAt: number;
  hostId: string;       // Persistent UUID of the host
  hostDisconnectedAt: number | null;
  state: 'waiting' | 'question' | 'estimation' | 'prepare';
  players: Player[];
  currentRound: CurrentRound | null;
  usedQuestionIds: number[];
}

export interface CurrentRound {
  questionId: number;
  sortingStarted: boolean;
  sortingFinished?: boolean;
  secondTurnStartPlayer?: boolean;
  estimationOrder: string[];      // Array of persistent player UUIDs
  currentTurnIndex: number;
  activePlayerId: string | null;  // Persistent player UUID
  placedPlayers: string[];        // Persistent player UUIDs
  initialOrder: string[];
  answers: Record<string, number>;        // playerId (UUID) -> answer
  playerOrderings: Record<string, string[]>; // playerId (UUID) -> ordering
}

export interface CreateRoomData {
  playerName: string;
  playerId: string; // Persistent UUID from localStorage
}

export interface CreateRoomResponse {
  success: boolean;
  roomCode?: string;
  shareLink?: string;
  game?: GameSession;
  error?: string;
}

export interface JoinRoomData {
  roomCode: string;
  playerName: string;
  playerId: string; // Persistent UUID from localStorage
}

export interface JoinRoomResponse {
  success: boolean;
  game?: GameSession;
  error?: string;
}

export interface StartGameData {
  roomCode: string;
  questionId: number;
}

export interface SubmitAnswerData {
  roomCode: string;
  answer: number;
}

export interface UpdateOrderData {
  roomCode: string;
  order: string[]; // Array of player IDs
}

export interface PlacePlayerData {
  roomCode: string;
  playerId: string;
}

export interface GenericRoomData {
  roomCode: string;
}

export interface GenericResponse {
  success: boolean;
  error?: string;
}

export interface StartNextQuestionData {
  roomCode: string;
  questionId: number;
}

export interface UpdatePlacedPlayersData {
  roomCode: string;
  placedPlayers: string[]; // Updated array of placed player IDs
  isSecondTurn?: boolean;  // True when P1 is finishing their second (final) turn
}
